### ISSUE TITLE
Add --version option

### ISSUE THREAD

**Issue by trentonyo** [Start-Out/todo-or-not#298]
Add an early exit print statement that echoes the current version

**Comment by MYusufY** [comment]
OK, i did it :) Only thing is, which version i have to put in the code? After adding the version number and testing, i will make a PR (pull request) soon :)

**Comment by MYusufY** [comment]
@trentonyo is it 00.10.15? (version) ?

**Comment by trentonyo** [comment]
> @trentonyo is it 00.10.15? (version) ?

For right now yes! 

See [this conversation](https://github.com/python-poetry/poetry/issues/273) for an example of how to pull the version dynamically from the pyproject.toml

Thank you for contributing!

**Comment by trentonyo** [comment]
https://typer.tiangolo.com/tutorial/options/version/

Additional helpful reading from the author of Typer

**Comment by MYusufY** [comment]
Thanks for answering and additional infos! I will make PR soon!

**Comment by MYusufY** [comment]
> g!

Thanks to you for this awesome tool!
