### ISSUE TITLE
Some way to ignore TODO's in code comments

### ISSUE THREAD

**Issue by mward25** [Start-Out/todo-or-not#319]
This would be very useful where the word todo is used in a comment.
For example, in the following code, their is no way to get rid of the todo issues.
```cpp
/**
 * @Breif adds todo to the todo_list
 * @Param todo_list The list to add to
 * @Param todo The Item to add to the list
*/
void add_to_todo_list(std::string& todo_list, std::string todo) {
     todo_list += "\n - ";
     todo_list += todo;
}
```
I propose we do the following to ignore todos.
```cpp
/**
 * @Breif adds todo to the todo_list [[IGNORE_TODO]]
 * @Param todo_list The list to add to [[IGNORE_TODO]]
 * @Param todo The Item to add to the list [[IGNORE_TODO]]
*/
void add_to_todo_list(std::string& todo_list, std::string todo) {
     todo_list += "\n - ";
     todo_list += todo;
}
```

**Comment by mward25** [comment]
Wait, sorry. I just realized the #todoon keyword.

**Comment by trentonyo** [comment]
Thank you for bringing it up though, I've added additional documentation and examples in the wiki: https://github.com/Start-Out/todo-or-not/wiki/Quick-Start#hit-detection
